User.create! name: 'Nikita Borgolov', email: 'nborgolov96@gmail.com', role: 'admin'
Genre.create! name: 'Фантастика'
Genre.create! name: 'Детектив'
Genre.create! name: 'Меллодрамма'
Genre.create! name: 'Драмма'
Genre.create! name: 'Триллер'
Genre.create! name: 'Ужасы'
Genre.create! name: 'Мистика'